spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dshop
    username: db-user
    password: db-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        use_sql: true
        format_sql: true
        show_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
